// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UI.Tests.FeaturesFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CentralPageFeature : Xunit.IClassFixture<CentralPageFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Main.feature"
#line hidden
        
        public CentralPageFeature(CentralPageFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Central Page", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Verify links")]
        [Xunit.TraitAttribute("FeatureTitle", "Central Page")]
        [Xunit.TraitAttribute("Description", "Verify links")]
        [Xunit.TraitAttribute("Category", "Browser_Chrome")]
        [Xunit.TraitAttribute("Category", "Central")]
        [Xunit.InlineDataAttribute("home", "17", new string[0])]
        public virtual void VerifyLinks(string page, string area, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Browser_Chrome",
                    "Central"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify links", null, @__tags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
testRunner.Given(string.Format("I navigated to {0} {1}", page, area), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Page",
                        "Menu",
                        "Count",
                        "Find",
                        "TestCase",
                        "Click"});
            table1.AddRow(new string[] {
                        "home",
                        "Locations",
                        "1",
                        "a[href*=locations]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "home",
                        "Treatments",
                        "34",
                        "a[href*=treatments]",
                        "17",
                        "false"});
            table1.AddRow(new string[] {
                        "home",
                        "Consultants",
                        "2",
                        "a[href*=consultants ]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "home",
                        "Patient information",
                        "8",
                        "a[href*=patient-information]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "home",
                        "How to book",
                        "7",
                        "a[href*=how-to-book]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "ourlocations",
                        "Our locations",
                        "40",
                        "a[href*=spirehealth]",
                        "16",
                        "true"});
            table1.AddRow(new string[] {
                        "Jobs",
                        "Recruitment",
                        "1",
                        "a[href*=recruitment]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "Jobs",
                        "Why work at Spire?",
                        "1",
                        "a[href*=why-work-at-spire]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "Jobs",
                        "Roles we offer",
                        "1",
                        "a[href*=roles-we-offer]",
                        "skip",
                        "false"});
            table1.AddRow(new string[] {
                        "Jobs",
                        "Profiles",
                        "1",
                        "a[href*=profiles]",
                        "skip",
                        "false"});
#line 7
testRunner.When("I count the number of links", ((string)(null)), table1, "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CentralPageFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CentralPageFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
